import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { analyzeCv } from "@/lib/scoring";

import { DE_CV, DE_JOB_AD, JOB_AD, STRONG_CV, TR_CV, TR_JOB_AD, WEAK_CV } from "./fixtures";

/**
 * docs/cost-weight-review.md is generated by scripts/dump-costs.mjs. A review
 * of a stale table reviews the wrong weights, so a finding the engine charges
 * must appear there with the cost it actually charges.
 */

const DOC = readFileSync(join(__dirname, "..", "apps", "web", "docs", "cost-weight-review.md"), "utf8");

function tableRow(id: string): string | undefined {
  return DOC.split("\n").find((line) => line.includes(`| \`${id}\` |`));
}

describe("cost weight review table", () => {
  const runs = [
    analyzeCv({ cvText: STRONG_CV }),
    analyzeCv({ cvText: STRONG_CV, jobDescription: JOB_AD }),
    analyzeCv({ cvText: WEAK_CV }),
    analyzeCv({ cvText: TR_CV, jobDescription: TR_JOB_AD }),
    analyzeCv({ cvText: DE_CV, jobDescription: DE_JOB_AD }),
    analyzeCv({ cvText: "" })
  ];

  it("lists every finding the engine charges, with a matching fixed cost", () => {
    for (const finding of runs.flatMap((result) => result.findings)) {
      const row = tableRow(finding.id);
      expect(row, `${finding.id} missing; run node scripts/dump-costs.mjs`).toBeDefined();
      const written = row?.split("|")[5]?.trim() ?? "";
      if (/^\d+$/.test(written)) expect(Number(written), finding.id).toBe(finding.cost);
    }
  });

  it("keeps the outcome section for a person to fill in", () => {
    expect(DOC).toContain("## Outcome");
    expect(DOC).toContain("A person fills this in");
  });
});
